# Generated by Django 5.2.5 on 2026-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume_version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
