# Generated by Django 5.2.5 on 2026-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobapplication_resume_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="interview_notes",
            field=models.TextField(blank=True),
        ),
    ]
