# Generated by Django 5.2.5 on 2026-06-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobapplication_interview_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
