# Generated by Django 6.0.7 on 2026-07-14 15:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobapplication_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="resume"
            ),
        ),
    ]
