# Generated by Django 6.0.7 on 2026-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobapplication_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume_file",
            field=models.URLField(blank=True, null=True),
        ),
    ]
